{{- if and .Values.ingress.enabled (not .Values.ingress.letsencrypt) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.ingress.host}}
spec:
  dnsNames:
    - {{.Values.ingress.host}}
  secretName: {{.Values.ingress.host}}
  issuerRef:
    name: selfsigned
    kind: Issuer
{{- end }}