{{- if and .Values.ingress.enabled .Values.ingress.letsencrypt }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.ingress.host}}
spec:
  dnsNames:
    - {{.Values.ingress.host}}
  secretName: {{.Values.ingress.host}}
  issuerRef:
    kind: Issuer
    name: pebble-issuer
    group: cert-manager.io
{{- end }}