{{- if and .Values.ingress.enabled .Values.ingress.letsencrypt }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pebble-issuer
spec:
  acme:
    skipTLSVerify: true
    server: https://pebble.pebble/dir
    privateKeySecretRef:
      name: pk-pebble-issuer
    solvers:
      - selector:
        http01:
          ingress:
            class: traefik
{{- end }}
