{{- if and .Values.ingress.enabled .Values.ingress.letsencrypt }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-ca-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressClassName: traefik
{{- end }}
