stage: prod
ingress:  
  enabled: true
  className: "traefik"
  hosts:
    - host: example-prod.local
      paths:
        - path: /
          pathType: ImplementationSpecific
opaqueSecret: bm94dHVhUHJvZFNlY3JldA==


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http