stage: dev

ingress:  
  enabled: true
  letsencrypt: false
  host: example-dev.local

opaqueSecret: bm94dHVhRGV2U2VjcmV0

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http