stage: dev
ingress:  
  enabled: true
  className: "traefik"
  hosts:
    - host: example-dev.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - hosts:
      - example-dev.local
     secretName: tls-cert

  annotations:
   traefik.ingress.kubernetes.io/router.entrypoints: "websecure"

opaqueSecret: bm94dHVhRGV2U2VjcmV0

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http