stage: prod

ingress:  
  enabled: true
  letsencrypt: false
  host: example-prod.local

opaqueSecret: bm94dHVhUHJvZFNlY3JldA==

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http