{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "staticapp.fullname" . }}
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{.Values.ingress.host}}`) && PathPrefix(`.well-known/acme-challenge`)
      kind: Rule
      services:
        - name: pebble.pebble
          port: https
    - match: Host(`{{.Values.ingress.host}}`)
      kind: Rule
      services:
        - name: {{ include "staticapp.fullname" $ }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: https-redirectscheme
  tls:
    {{- if .Values.ingress.letsencrypt}}
    secretName: letsencrypt-ca-secret
    {{- else }}
    secretName: {{.Values.ingress.host}}
    {{- end }}
{{- end }}